/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package sudoku

import kotlin.test.Test

class SudokuTest {
    @Test fun emptyBoard() {
        val board = arrayOf(
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0),
            arrayOf(0, 0, 0, 0, 0, 0, 0, 0, 0)
        )

        val underTest = Sudoku(board)
   }

    @Test fun unsolvedBoard() {
        val board = arrayOf(
            arrayOf(9, 0, 0, 0, 1, 0, 0, 0, 8),
            arrayOf(0, 1, 0, 5, 0, 0, 9, 0, 0),
            arrayOf(6, 0, 0, 4, 0, 0, 2, 5, 0),
            arrayOf(1, 0, 0, 7, 2, 0, 3, 0, 0),
            arrayOf(0, 0, 0, 9, 0, 3, 0, 0, 0),
            arrayOf(0, 0, 9, 0, 6, 8, 0, 0, 2),
            arrayOf(0, 6, 1, 0, 0, 5, 0, 0, 7),
            arrayOf(0, 0, 8, 0, 0, 9, 0, 1, 0),
            arrayOf(7, 0, 0, 0, 3, 0, 0, 0, 5)
        )

        val underTest = Sudoku(board)
   }
}
